### ISSUE TITLE
Right click on code block crashes Discord

### ISSUE THREAD

**Issue by asportnoy** [lorencerri/powercord-reverse-image-search#8]
Right clicking anywhere on a message with a code block causes Discord to crash. Disabling this plugin resolves this issue, so I know it has to do with this plugin.

Canary 97971 (b2a656c) Host 0.0.277 OS X 10.15.7 (21.1.0)
Powercord v2 [49d2cae]
Plugin v2.0.0

**Comment by lorencerri** [comment]
That’s an unusual issue, I’ll try to reproduce it later tonight to see how
I can go around fixing it.

**Comment by lorencerri** [comment]
I've pushed an update that solved the issue in my testing (dfc952f). If it persists for you, please let me know so I can reopen this. Thank you!

**Comment by asportnoy** [comment]
Hi, I updated to dfc952f40c895409c8640e00641cfb08ee90a12a and unfortunately the issue persists. I would send console logs for the issue but when Discord crashes it closes the console so I am unable to see them.

**Comment by asportnoy** [comment]
Found a fix! On: https://github.com/lorencerri/powercord-reverse-image-search/blob/dfc952f40c895409c8640e00641cfb08ee90a12a/index.js#L47
```js
// BEFORE
let target = props[0].target;

// AFTER
let target = props[0]?.target;
```
(Note the `?`)

**Comment by lorencerri** [comment]
Pushed, thank you!

**Comment by asportnoy** [comment]
So apparently I was wrong about the previous fix. It worked before but now it doesn't. After more investigating it looks like the issue is with the while loop that finds an image element. Perhaps it is getting overloaded? I don't know. However, I replaced it with `target.querySelector` and that did work.

```js
// Recursively select target image
let target = props[0]?.target;
if (!target) return res;
if (target.tagName.toLowerCase() !== 'img') target = target.querySelector('img');
    
// If target isn't an image, return
if (!target || target.tagName.toLowerCase() !== 'img') return res;
```
I confirmed that this approach shows the context menu on messages/elements with images but not those without.

**Comment by SammyWhamy** [comment]
Is this being worked on? I'm currently experiencing the same issue, an update with a fix would be nice

**Comment by lorencerri** [comment]
> Is this being worked on? I'm currently experiencing the same issue, an update with a fix would be nice

Pushed a temporary fix that should resolve the crashing (b4af950), I'll look for a permanent solution to remedy the issue.

**Comment by asportnoy** [comment]
I posted some code above that i've been using with no issues.

**Comment by lorencerri** [comment]
> I posted some code above that i've been using with no issues.

Oh I'm not sure how I missed that, pushed the update, appreciate it!
